name: Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform-prod:
    uses: ./.github/workflows/terraform-template.yml
    with:
      environment: production
      working_directory: aws/prod
    secrets: inherit # This will pass all repository secrets to the reusable workflow
