# .github/workflows/terraform-pipeline.yml
name: Terraform CI/CD
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  prod-fmt:
    uses: ./.github/workflows/terraform-fmt.yml
    with:
      environment: prod
      working_directory: aws/prod

  prod-plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: prod
      working_directory: aws/prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY: ${{ secrets.TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY }}

  prod-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ prod-fmt, prod-plan ]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: prod
      working_directory: aws/prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY: ${{ secrets.TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY }}
