name: Terraform Plan
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_directory:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY:
        required: true

jobs:
  terraform-plan:
    name: ${{ inputs.environment }}-terraform-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: terraform init
        working-directory: ${{ inputs.working_directory }}
      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        env:
          TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY: ${{ secrets.TF_VAR_PROJECTSPRINT_VM_PUBLIC_KEY }}
        run: terraform plan -no-color
